// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComplexTest.proto

package com.von.rpc.common.entity;

public final class ComplexResult {
  private ComplexResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ComplexTestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.von.rpc.common.netty.proto.Result result = 1;
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    java.util.List<com.von.rpc.common.entity.ComplexResult.Result> 
        getResultList();
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    com.von.rpc.common.entity.ComplexResult.Result getResult(int index);
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    java.util.List<? extends com.von.rpc.common.entity.ComplexResult.ResultOrBuilder> 
        getResultOrBuilderList();
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    com.von.rpc.common.entity.ComplexResult.ResultOrBuilder getResultOrBuilder(
        int index);

    // optional .com.von.rpc.common.netty.proto.Exception exception = 2;
    /**
     * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
     */
    boolean hasException();
    /**
     * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
     */
    com.von.rpc.common.entity.ComplexResult.Exception getException();
    /**
     * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
     */
    com.von.rpc.common.entity.ComplexResult.ExceptionOrBuilder getExceptionOrBuilder();
  }
  /**
   * Protobuf type {@code com.von.rpc.common.netty.proto.ComplexTest}
   */
  public static final class ComplexTest extends
      com.google.protobuf.GeneratedMessage
      implements ComplexTestOrBuilder {
    // Use ComplexTest.newBuilder() to construct.
    private ComplexTest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ComplexTest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ComplexTest defaultInstance;
    public static ComplexTest getDefaultInstance() {
      return defaultInstance;
    }

    public ComplexTest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ComplexTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result_ = new java.util.ArrayList<com.von.rpc.common.entity.ComplexResult.Result>();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.add(input.readMessage(com.von.rpc.common.entity.ComplexResult.Result.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.von.rpc.common.entity.ComplexResult.Exception.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = exception_.toBuilder();
              }
              exception_ = input.readMessage(com.von.rpc.common.entity.ComplexResult.Exception.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(exception_);
                exception_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_ComplexTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_ComplexTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.von.rpc.common.entity.ComplexResult.ComplexTest.class, com.von.rpc.common.entity.ComplexResult.ComplexTest.Builder.class);
    }

    public static com.google.protobuf.Parser<ComplexTest> PARSER =
        new com.google.protobuf.AbstractParser<ComplexTest>() {
      public ComplexTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComplexTest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ComplexTest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .com.von.rpc.common.netty.proto.Result result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.util.List<com.von.rpc.common.entity.ComplexResult.Result> result_;
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    public java.util.List<com.von.rpc.common.entity.ComplexResult.Result> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    public java.util.List<? extends com.von.rpc.common.entity.ComplexResult.ResultOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    public com.von.rpc.common.entity.ComplexResult.Result getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
     */
    public com.von.rpc.common.entity.ComplexResult.ResultOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    // optional .com.von.rpc.common.netty.proto.Exception exception = 2;
    public static final int EXCEPTION_FIELD_NUMBER = 2;
    private com.von.rpc.common.entity.ComplexResult.Exception exception_;
    /**
     * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
     */
    public boolean hasException() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
     */
    @Override
    public com.von.rpc.common.entity.ComplexResult.Exception getException() {
      return exception_;
    }
    /**
     * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
     */
    public com.von.rpc.common.entity.ComplexResult.ExceptionOrBuilder getExceptionOrBuilder() {
      return exception_;
    }

    private void initFields() {
      result_ = java.util.Collections.emptyList();
      exception_ = com.von.rpc.common.entity.ComplexResult.Exception.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getResultCount(); i++) {
        if (!getResult(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasException()) {
        if (!getException().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(1, result_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, exception_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, exception_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.ComplexTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.von.rpc.common.entity.ComplexResult.ComplexTest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.von.rpc.common.netty.proto.ComplexTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.von.rpc.common.entity.ComplexResult.ComplexTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_ComplexTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_ComplexTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.von.rpc.common.entity.ComplexResult.ComplexTest.class, com.von.rpc.common.entity.ComplexResult.ComplexTest.Builder.class);
      }

      // Construct using com.von.rpc.common.entity.ComplexResult.ComplexTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
          getExceptionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultBuilder_.clear();
        }
        if (exceptionBuilder_ == null) {
          exception_ = com.von.rpc.common.entity.ComplexResult.Exception.getDefaultInstance();
        } else {
          exceptionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_ComplexTest_descriptor;
      }

      public com.von.rpc.common.entity.ComplexResult.ComplexTest getDefaultInstanceForType() {
        return com.von.rpc.common.entity.ComplexResult.ComplexTest.getDefaultInstance();
      }

      public com.von.rpc.common.entity.ComplexResult.ComplexTest build() {
        com.von.rpc.common.entity.ComplexResult.ComplexTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.von.rpc.common.entity.ComplexResult.ComplexTest buildPartial() {
        com.von.rpc.common.entity.ComplexResult.ComplexTest result = new com.von.rpc.common.entity.ComplexResult.ComplexTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (exceptionBuilder_ == null) {
          result.exception_ = exception_;
        } else {
          result.exception_ = exceptionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.von.rpc.common.entity.ComplexResult.ComplexTest) {
          return mergeFrom((com.von.rpc.common.entity.ComplexResult.ComplexTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.von.rpc.common.entity.ComplexResult.ComplexTest other) {
        if (other == com.von.rpc.common.entity.ComplexResult.ComplexTest.getDefaultInstance()) return this;
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        if (other.hasException()) {
          mergeException(other.getException());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getResultCount(); i++) {
          if (!getResult(i).isInitialized()) {
            
            return false;
          }
        }
        if (hasException()) {
          if (!getException().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.von.rpc.common.entity.ComplexResult.ComplexTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.von.rpc.common.entity.ComplexResult.ComplexTest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.von.rpc.common.netty.proto.Result result = 1;
      private java.util.List<com.von.rpc.common.entity.ComplexResult.Result> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = new java.util.ArrayList<com.von.rpc.common.entity.ComplexResult.Result>(result_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.von.rpc.common.entity.ComplexResult.Result, com.von.rpc.common.entity.ComplexResult.Result.Builder, com.von.rpc.common.entity.ComplexResult.ResultOrBuilder> resultBuilder_;

      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public java.util.List<com.von.rpc.common.entity.ComplexResult.Result> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public com.von.rpc.common.entity.ComplexResult.Result getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder setResult(
          int index, com.von.rpc.common.entity.ComplexResult.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder setResult(
          int index, com.von.rpc.common.entity.ComplexResult.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder addResult(com.von.rpc.common.entity.ComplexResult.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder addResult(
          int index, com.von.rpc.common.entity.ComplexResult.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder addResult(
          com.von.rpc.common.entity.ComplexResult.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder addResult(
          int index, com.von.rpc.common.entity.ComplexResult.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends com.von.rpc.common.entity.ComplexResult.Result> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          super.addAll(values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public com.von.rpc.common.entity.ComplexResult.Result.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public com.von.rpc.common.entity.ComplexResult.ResultOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public java.util.List<? extends com.von.rpc.common.entity.ComplexResult.ResultOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public com.von.rpc.common.entity.ComplexResult.Result.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            com.von.rpc.common.entity.ComplexResult.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public com.von.rpc.common.entity.ComplexResult.Result.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, com.von.rpc.common.entity.ComplexResult.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .com.von.rpc.common.netty.proto.Result result = 1;</code>
       */
      public java.util.List<com.von.rpc.common.entity.ComplexResult.Result.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.von.rpc.common.entity.ComplexResult.Result, com.von.rpc.common.entity.ComplexResult.Result.Builder, com.von.rpc.common.entity.ComplexResult.ResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.von.rpc.common.entity.ComplexResult.Result, com.von.rpc.common.entity.ComplexResult.Result.Builder, com.von.rpc.common.entity.ComplexResult.ResultOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // optional .com.von.rpc.common.netty.proto.Exception exception = 2;
      private com.von.rpc.common.entity.ComplexResult.Exception exception_ = com.von.rpc.common.entity.ComplexResult.Exception.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.von.rpc.common.entity.ComplexResult.Exception, com.von.rpc.common.entity.ComplexResult.Exception.Builder, com.von.rpc.common.entity.ComplexResult.ExceptionOrBuilder> exceptionBuilder_;
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      public boolean hasException() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      @Override
      public com.von.rpc.common.entity.ComplexResult.Exception getException() {
        if (exceptionBuilder_ == null) {
          return exception_;
        } else {
          return exceptionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      public Builder setException(com.von.rpc.common.entity.ComplexResult.Exception value) {
        if (exceptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          exception_ = value;
          onChanged();
        } else {
          exceptionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      public Builder setException(
          com.von.rpc.common.entity.ComplexResult.Exception.Builder builderForValue) {
        if (exceptionBuilder_ == null) {
          exception_ = builderForValue.build();
          onChanged();
        } else {
          exceptionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      public Builder mergeException(com.von.rpc.common.entity.ComplexResult.Exception value) {
        if (exceptionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              exception_ != com.von.rpc.common.entity.ComplexResult.Exception.getDefaultInstance()) {
            exception_ =
              com.von.rpc.common.entity.ComplexResult.Exception.newBuilder(exception_).mergeFrom(value).buildPartial();
          } else {
            exception_ = value;
          }
          onChanged();
        } else {
          exceptionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      public Builder clearException() {
        if (exceptionBuilder_ == null) {
          exception_ = com.von.rpc.common.entity.ComplexResult.Exception.getDefaultInstance();
          onChanged();
        } else {
          exceptionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      public com.von.rpc.common.entity.ComplexResult.Exception.Builder getExceptionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getExceptionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      public com.von.rpc.common.entity.ComplexResult.ExceptionOrBuilder getExceptionOrBuilder() {
        if (exceptionBuilder_ != null) {
          return exceptionBuilder_.getMessageOrBuilder();
        } else {
          return exception_;
        }
      }
      /**
       * <code>optional .com.von.rpc.common.netty.proto.Exception exception = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.von.rpc.common.entity.ComplexResult.Exception, com.von.rpc.common.entity.ComplexResult.Exception.Builder, com.von.rpc.common.entity.ComplexResult.ExceptionOrBuilder> 
          getExceptionFieldBuilder() {
        if (exceptionBuilder_ == null) {
          exceptionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.von.rpc.common.entity.ComplexResult.Exception, com.von.rpc.common.entity.ComplexResult.Exception.Builder, com.von.rpc.common.entity.ComplexResult.ExceptionOrBuilder>(
                  exception_,
                  getParentForChildren(),
                  isClean());
          exception_ = null;
        }
        return exceptionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.von.rpc.common.netty.proto.ComplexTest)
    }

    static {
      defaultInstance = new ComplexTest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.von.rpc.common.netty.proto.ComplexTest)
  }

  public interface ResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string requestId = 1;
    /**
     * <code>required string requestId = 1;</code>
     */
    boolean hasRequestId();
    /**
     * <code>required string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>required string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    // required string responseId = 2;
    /**
     * <code>required string responseId = 2;</code>
     */
    boolean hasResponseId();
    /**
     * <code>required string responseId = 2;</code>
     */
    java.lang.String getResponseId();
    /**
     * <code>required string responseId = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponseIdBytes();

    // required string data = 3;
    /**
     * <code>required string data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>required string data = 3;</code>
     */
    java.lang.String getData();
    /**
     * <code>required string data = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code com.von.rpc.common.netty.proto.Result}
   */
  public static final class Result extends
      com.google.protobuf.GeneratedMessage
      implements ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Result defaultInstance;
    public static Result getDefaultInstance() {
      return defaultInstance;
    }

    public Result getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              responseId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.von.rpc.common.entity.ComplexResult.Result.class, com.von.rpc.common.entity.ComplexResult.Result.Builder.class);
    }

    public static com.google.protobuf.Parser<Result> PARSER =
        new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string requestId = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private java.lang.Object requestId_;
    /**
     * <code>required string requestId = 1;</code>
     */
    @Override
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string responseId = 2;
    public static final int RESPONSEID_FIELD_NUMBER = 2;
    private java.lang.Object responseId_;
    /**
     * <code>required string responseId = 2;</code>
     */
    public boolean hasResponseId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string responseId = 2;</code>
     */
    public java.lang.String getResponseId() {
      java.lang.Object ref = responseId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          responseId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string responseId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponseIdBytes() {
      java.lang.Object ref = responseId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.lang.Object data_;
    /**
     * <code>required string data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      requestId_ = "";
      responseId_ = "";
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponseId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResponseIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResponseIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.von.rpc.common.entity.ComplexResult.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.von.rpc.common.entity.ComplexResult.Result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.von.rpc.common.netty.proto.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.von.rpc.common.entity.ComplexResult.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.von.rpc.common.entity.ComplexResult.Result.class, com.von.rpc.common.entity.ComplexResult.Result.Builder.class);
      }

      // Construct using com.von.rpc.common.entity.ComplexResult.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        responseId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Result_descriptor;
      }

      public com.von.rpc.common.entity.ComplexResult.Result getDefaultInstanceForType() {
        return com.von.rpc.common.entity.ComplexResult.Result.getDefaultInstance();
      }

      public com.von.rpc.common.entity.ComplexResult.Result build() {
        com.von.rpc.common.entity.ComplexResult.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.von.rpc.common.entity.ComplexResult.Result buildPartial() {
        com.von.rpc.common.entity.ComplexResult.Result result = new com.von.rpc.common.entity.ComplexResult.Result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseId_ = responseId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.von.rpc.common.entity.ComplexResult.Result) {
          return mergeFrom((com.von.rpc.common.entity.ComplexResult.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.von.rpc.common.entity.ComplexResult.Result other) {
        if (other == com.von.rpc.common.entity.ComplexResult.Result.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000001;
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.hasResponseId()) {
          bitField0_ |= 0x00000002;
          responseId_ = other.responseId_;
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000004;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasResponseId()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.von.rpc.common.entity.ComplexResult.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.von.rpc.common.entity.ComplexResult.Result) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string requestId = 1;
      private java.lang.Object requestId_ = "";
      /**
       * <code>required string requestId = 1;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>required string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }

      // required string responseId = 2;
      private java.lang.Object responseId_ = "";
      /**
       * <code>required string responseId = 2;</code>
       */
      public boolean hasResponseId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string responseId = 2;</code>
       */
      public java.lang.String getResponseId() {
        java.lang.Object ref = responseId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          responseId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string responseId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseIdBytes() {
        java.lang.Object ref = responseId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string responseId = 2;</code>
       */
      public Builder setResponseId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string responseId = 2;</code>
       */
      public Builder clearResponseId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseId_ = getDefaultInstance().getResponseId();
        onChanged();
        return this;
      }
      /**
       * <code>required string responseId = 2;</code>
       */
      public Builder setResponseIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseId_ = value;
        onChanged();
        return this;
      }

      // required string data = 3;
      private java.lang.Object data_ = "";
      /**
       * <code>required string data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string data = 3;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data = 3;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 3;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.von.rpc.common.netty.proto.Result)
    }

    static {
      defaultInstance = new Result(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.von.rpc.common.netty.proto.Result)
  }

  public interface ExceptionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string exClazz = 1;
    /**
     * <code>required string exClazz = 1;</code>
     */
    boolean hasExClazz();
    /**
     * <code>required string exClazz = 1;</code>
     */
    java.lang.String getExClazz();
    /**
     * <code>required string exClazz = 1;</code>
     */
    com.google.protobuf.ByteString
        getExClazzBytes();

    // required string exMessage = 2;
    /**
     * <code>required string exMessage = 2;</code>
     */
    boolean hasExMessage();
    /**
     * <code>required string exMessage = 2;</code>
     */
    java.lang.String getExMessage();
    /**
     * <code>required string exMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getExMessageBytes();
  }
  /**
   * Protobuf type {@code com.von.rpc.common.netty.proto.Exception}
   */
  public static final class Exception extends
      com.google.protobuf.GeneratedMessage
      implements ExceptionOrBuilder {
    // Use Exception.newBuilder() to construct.
    private Exception(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Exception(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Exception defaultInstance;
    public static Exception getDefaultInstance() {
      return defaultInstance;
    }

    public Exception getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Exception(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              exClazz_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              exMessage_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Exception_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Exception_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.von.rpc.common.entity.ComplexResult.Exception.class, com.von.rpc.common.entity.ComplexResult.Exception.Builder.class);
    }

    public static com.google.protobuf.Parser<Exception> PARSER =
        new com.google.protobuf.AbstractParser<Exception>() {
      public Exception parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Exception(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Exception> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string exClazz = 1;
    public static final int EXCLAZZ_FIELD_NUMBER = 1;
    private java.lang.Object exClazz_;
    /**
     * <code>required string exClazz = 1;</code>
     */
    public boolean hasExClazz() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string exClazz = 1;</code>
     */
    public java.lang.String getExClazz() {
      java.lang.Object ref = exClazz_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exClazz_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string exClazz = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExClazzBytes() {
      java.lang.Object ref = exClazz_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exClazz_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string exMessage = 2;
    public static final int EXMESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object exMessage_;
    /**
     * <code>required string exMessage = 2;</code>
     */
    public boolean hasExMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string exMessage = 2;</code>
     */
    public java.lang.String getExMessage() {
      java.lang.Object ref = exMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string exMessage = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getExMessageBytes() {
      java.lang.Object ref = exMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      exClazz_ = "";
      exMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasExClazz()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getExClazzBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getExMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getExClazzBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getExMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.von.rpc.common.entity.ComplexResult.Exception parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.von.rpc.common.entity.ComplexResult.Exception parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.von.rpc.common.entity.ComplexResult.Exception prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.von.rpc.common.netty.proto.Exception}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.von.rpc.common.entity.ComplexResult.ExceptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Exception_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Exception_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.von.rpc.common.entity.ComplexResult.Exception.class, com.von.rpc.common.entity.ComplexResult.Exception.Builder.class);
      }

      // Construct using com.von.rpc.common.entity.ComplexResult.Exception.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        exClazz_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        exMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.von.rpc.common.entity.ComplexResult.internal_static_com_von_rpc_common_netty_proto_Exception_descriptor;
      }

      public com.von.rpc.common.entity.ComplexResult.Exception getDefaultInstanceForType() {
        return com.von.rpc.common.entity.ComplexResult.Exception.getDefaultInstance();
      }

      public com.von.rpc.common.entity.ComplexResult.Exception build() {
        com.von.rpc.common.entity.ComplexResult.Exception result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.von.rpc.common.entity.ComplexResult.Exception buildPartial() {
        com.von.rpc.common.entity.ComplexResult.Exception result = new com.von.rpc.common.entity.ComplexResult.Exception(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exClazz_ = exClazz_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.exMessage_ = exMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.von.rpc.common.entity.ComplexResult.Exception) {
          return mergeFrom((com.von.rpc.common.entity.ComplexResult.Exception)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.von.rpc.common.entity.ComplexResult.Exception other) {
        if (other == com.von.rpc.common.entity.ComplexResult.Exception.getDefaultInstance()) return this;
        if (other.hasExClazz()) {
          bitField0_ |= 0x00000001;
          exClazz_ = other.exClazz_;
          onChanged();
        }
        if (other.hasExMessage()) {
          bitField0_ |= 0x00000002;
          exMessage_ = other.exMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasExClazz()) {
          
          return false;
        }
        if (!hasExMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.von.rpc.common.entity.ComplexResult.Exception parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.von.rpc.common.entity.ComplexResult.Exception) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string exClazz = 1;
      private java.lang.Object exClazz_ = "";
      /**
       * <code>required string exClazz = 1;</code>
       */
      public boolean hasExClazz() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string exClazz = 1;</code>
       */
      public java.lang.String getExClazz() {
        java.lang.Object ref = exClazz_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          exClazz_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string exClazz = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExClazzBytes() {
        java.lang.Object ref = exClazz_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exClazz_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string exClazz = 1;</code>
       */
      public Builder setExClazz(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        exClazz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string exClazz = 1;</code>
       */
      public Builder clearExClazz() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exClazz_ = getDefaultInstance().getExClazz();
        onChanged();
        return this;
      }
      /**
       * <code>required string exClazz = 1;</code>
       */
      public Builder setExClazzBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        exClazz_ = value;
        onChanged();
        return this;
      }

      // required string exMessage = 2;
      private java.lang.Object exMessage_ = "";
      /**
       * <code>required string exMessage = 2;</code>
       */
      public boolean hasExMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string exMessage = 2;</code>
       */
      public java.lang.String getExMessage() {
        java.lang.Object ref = exMessage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          exMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string exMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getExMessageBytes() {
        java.lang.Object ref = exMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string exMessage = 2;</code>
       */
      public Builder setExMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        exMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string exMessage = 2;</code>
       */
      public Builder clearExMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        exMessage_ = getDefaultInstance().getExMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string exMessage = 2;</code>
       */
      public Builder setExMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        exMessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.von.rpc.common.netty.proto.Exception)
    }

    static {
      defaultInstance = new Exception(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.von.rpc.common.netty.proto.Exception)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_von_rpc_common_netty_proto_ComplexTest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_von_rpc_common_netty_proto_ComplexTest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_von_rpc_common_netty_proto_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_von_rpc_common_netty_proto_Result_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_von_rpc_common_netty_proto_Exception_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_von_rpc_common_netty_proto_Exception_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ComplexTest.proto\022\036com.von.rpc.common." +
      "netty.proto\"\203\001\n\013ComplexTest\0226\n\006result\030\001 " +
      "\003(\0132&.com.von.rpc.common.netty.proto.Res" +
      "ult\022<\n\texception\030\002 \001(\0132).com.von.rpc.com" +
      "mon.netty.proto.Exception\"=\n\006Result\022\021\n\tr" +
      "equestId\030\001 \002(\t\022\022\n\nresponseId\030\002 \002(\t\022\014\n\004da" +
      "ta\030\003 \002(\t\"/\n\tException\022\017\n\007exClazz\030\001 \002(\t\022\021" +
      "\n\texMessage\030\002 \002(\tB*\n\031com.von.rpc.common." +
      "entityB\rComplexResult"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_von_rpc_common_netty_proto_ComplexTest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_von_rpc_common_netty_proto_ComplexTest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_von_rpc_common_netty_proto_ComplexTest_descriptor,
              new java.lang.String[] { "Result", "Exception", });
          internal_static_com_von_rpc_common_netty_proto_Result_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_von_rpc_common_netty_proto_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_von_rpc_common_netty_proto_Result_descriptor,
              new java.lang.String[] { "RequestId", "ResponseId", "Data", });
          internal_static_com_von_rpc_common_netty_proto_Exception_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_von_rpc_common_netty_proto_Exception_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_von_rpc_common_netty_proto_Exception_descriptor,
              new java.lang.String[] { "ExClazz", "ExMessage", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
