// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBufMRpcRequest.proto

package com.von.rpc.common.entity;

public final class MRpcProtoBufRequest {
  private MRpcProtoBufRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoBufMRpcRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string requestId = 1;
    /**
     * <code>required string requestId = 1;</code>
     *
     * <pre>
     *请求id
     * </pre>
     */
    boolean hasRequestId();
    /**
     * <code>required string requestId = 1;</code>
     *
     * <pre>
     *请求id
     * </pre>
     */
    java.lang.String getRequestId();
    /**
     * <code>required string requestId = 1;</code>
     *
     * <pre>
     *请求id
     * </pre>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    // required string requestUrl = 2;
    /**
     * <code>required string requestUrl = 2;</code>
     *
     * <pre>
     *请求参数
     * </pre>
     */
    boolean hasRequestUrl();
    /**
     * <code>required string requestUrl = 2;</code>
     *
     * <pre>
     *请求参数
     * </pre>
     */
    java.lang.String getRequestUrl();
    /**
     * <code>required string requestUrl = 2;</code>
     *
     * <pre>
     *请求参数
     * </pre>
     */
    com.google.protobuf.ByteString
        getRequestUrlBytes();
  }
  /**
   * Protobuf type {@code com.von.rpc.common.netty.proto.ProtoBufMRpcRequest}
   *
   * <pre>
   *protoc.exe -I=./ ProtoBufMRpcRequest.proto --java_out=D:/myTest/rpc/rpc-common/src/main/java
   *protoc使用注意事项：-I的路径后面跟的文件一定要隔开一个空格
   * </pre>
   */
  public static final class ProtoBufMRpcRequest extends
      com.google.protobuf.GeneratedMessage
      implements ProtoBufMRpcRequestOrBuilder {
    // Use ProtoBufMRpcRequest.newBuilder() to construct.
    private ProtoBufMRpcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoBufMRpcRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoBufMRpcRequest defaultInstance;
    public static ProtoBufMRpcRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoBufMRpcRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoBufMRpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              requestUrl_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.class, com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoBufMRpcRequest> PARSER =
        new com.google.protobuf.AbstractParser<ProtoBufMRpcRequest>() {
      public ProtoBufMRpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoBufMRpcRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBufMRpcRequest> getParserForType() {
      return PARSER;
    }

    public interface MRpcMethodOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // repeated string args = 2;
      /**
       * <code>repeated string args = 2;</code>
       */
      java.util.List<java.lang.String>
      getArgsList();
      /**
       * <code>repeated string args = 2;</code>
       */
      int getArgsCount();
      /**
       * <code>repeated string args = 2;</code>
       */
      java.lang.String getArgs(int index);
      /**
       * <code>repeated string args = 2;</code>
       */
      com.google.protobuf.ByteString
          getArgsBytes(int index);

      // repeated string paramType = 3;
      /**
       * <code>repeated string paramType = 3;</code>
       */
      java.util.List<java.lang.String>
      getParamTypeList();
      /**
       * <code>repeated string paramType = 3;</code>
       */
      int getParamTypeCount();
      /**
       * <code>repeated string paramType = 3;</code>
       */
      java.lang.String getParamType(int index);
      /**
       * <code>repeated string paramType = 3;</code>
       */
      com.google.protobuf.ByteString
          getParamTypeBytes(int index);
    }
    /**
     * Protobuf type {@code com.von.rpc.common.netty.proto.ProtoBufMRpcRequest.MRpcMethod}
     */
    public static final class MRpcMethod extends
        com.google.protobuf.GeneratedMessage
        implements MRpcMethodOrBuilder {
      // Use MRpcMethod.newBuilder() to construct.
      private MRpcMethod(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MRpcMethod(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MRpcMethod defaultInstance;
      public static MRpcMethod getDefaultInstance() {
        return defaultInstance;
      }

      public MRpcMethod getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MRpcMethod(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  args_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                args_.add(input.readBytes());
                break;
              }
              case 26: {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  paramType_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000004;
                }
                paramType_.add(input.readBytes());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            args_ = new com.google.protobuf.UnmodifiableLazyStringList(args_);
          }
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            paramType_ = new com.google.protobuf.UnmodifiableLazyStringList(paramType_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod.class, com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod.Builder.class);
      }

      public static com.google.protobuf.Parser<MRpcMethod> PARSER =
          new com.google.protobuf.AbstractParser<MRpcMethod>() {
        public MRpcMethod parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MRpcMethod(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MRpcMethod> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // repeated string args = 2;
      public static final int ARGS_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList args_;
      /**
       * <code>repeated string args = 2;</code>
       */
      public java.util.List<java.lang.String>
          getArgsList() {
        return args_;
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public int getArgsCount() {
        return args_.size();
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public java.lang.String getArgs(int index) {
        return args_.get(index);
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArgsBytes(int index) {
        return args_.getByteString(index);
      }

      // repeated string paramType = 3;
      public static final int PARAMTYPE_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList paramType_;
      /**
       * <code>repeated string paramType = 3;</code>
       */
      public java.util.List<java.lang.String>
          getParamTypeList() {
        return paramType_;
      }
      /**
       * <code>repeated string paramType = 3;</code>
       */
      public int getParamTypeCount() {
        return paramType_.size();
      }
      /**
       * <code>repeated string paramType = 3;</code>
       */
      public java.lang.String getParamType(int index) {
        return paramType_.get(index);
      }
      /**
       * <code>repeated string paramType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getParamTypeBytes(int index) {
        return paramType_.getByteString(index);
      }

      private void initFields() {
        name_ = "";
        args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        paramType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        for (int i = 0; i < args_.size(); i++) {
          output.writeBytes(2, args_.getByteString(i));
        }
        for (int i = 0; i < paramType_.size(); i++) {
          output.writeBytes(3, paramType_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        {
          int dataSize = 0;
          for (int i = 0; i < args_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(args_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getArgsList().size();
        }
        {
          int dataSize = 0;
          for (int i = 0; i < paramType_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(paramType_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getParamTypeList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.von.rpc.common.netty.proto.ProtoBufMRpcRequest.MRpcMethod}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethodOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod.class, com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod.Builder.class);
        }

        // Construct using com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          paramType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_descriptor;
        }

        public com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod getDefaultInstanceForType() {
          return com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod.getDefaultInstance();
        }

        public com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod build() {
          com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod buildPartial() {
          com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod result = new com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            args_ = new com.google.protobuf.UnmodifiableLazyStringList(
                args_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.args_ = args_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            paramType_ = new com.google.protobuf.UnmodifiableLazyStringList(
                paramType_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.paramType_ = paramType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod) {
            return mergeFrom((com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod other) {
          if (other == com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (!other.args_.isEmpty()) {
            if (args_.isEmpty()) {
              args_ = other.args_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureArgsIsMutable();
              args_.addAll(other.args_);
            }
            onChanged();
          }
          if (!other.paramType_.isEmpty()) {
            if (paramType_.isEmpty()) {
              paramType_ = other.paramType_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureParamTypeIsMutable();
              paramType_.addAll(other.paramType_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.MRpcMethod) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // repeated string args = 2;
        private com.google.protobuf.LazyStringList args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureArgsIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            args_ = new com.google.protobuf.LazyStringArrayList(args_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public java.util.List<java.lang.String>
            getArgsList() {
          return java.util.Collections.unmodifiableList(args_);
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public int getArgsCount() {
          return args_.size();
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public java.lang.String getArgs(int index) {
          return args_.get(index);
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public com.google.protobuf.ByteString
            getArgsBytes(int index) {
          return args_.getByteString(index);
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public Builder setArgs(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
          args_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public Builder addArgs(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
          args_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public Builder addAllArgs(
            java.lang.Iterable<java.lang.String> values) {
          ensureArgsIsMutable();
          super.addAll(values, args_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public Builder clearArgs() {
          args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string args = 2;</code>
         */
        public Builder addArgsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
          args_.add(value);
          onChanged();
          return this;
        }

        // repeated string paramType = 3;
        private com.google.protobuf.LazyStringList paramType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureParamTypeIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            paramType_ = new com.google.protobuf.LazyStringArrayList(paramType_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public java.util.List<java.lang.String>
            getParamTypeList() {
          return java.util.Collections.unmodifiableList(paramType_);
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public int getParamTypeCount() {
          return paramType_.size();
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public java.lang.String getParamType(int index) {
          return paramType_.get(index);
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public com.google.protobuf.ByteString
            getParamTypeBytes(int index) {
          return paramType_.getByteString(index);
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public Builder setParamType(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypeIsMutable();
          paramType_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public Builder addParamType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypeIsMutable();
          paramType_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public Builder addAllParamType(
            java.lang.Iterable<java.lang.String> values) {
          ensureParamTypeIsMutable();
          super.addAll(values, paramType_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public Builder clearParamType() {
          paramType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string paramType = 3;</code>
         */
        public Builder addParamTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypeIsMutable();
          paramType_.add(value);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.von.rpc.common.netty.proto.ProtoBufMRpcRequest.MRpcMethod)
      }

      static {
        defaultInstance = new MRpcMethod(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.von.rpc.common.netty.proto.ProtoBufMRpcRequest.MRpcMethod)
    }

    private int bitField0_;
    // required string requestId = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private java.lang.Object requestId_;
    /**
     * <code>required string requestId = 1;</code>
     *
     * <pre>
     *请求id
     * </pre>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string requestId = 1;</code>
     *
     * <pre>
     *请求id
     * </pre>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requestId = 1;</code>
     *
     * <pre>
     *请求id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string requestUrl = 2;
    public static final int REQUESTURL_FIELD_NUMBER = 2;
    private java.lang.Object requestUrl_;
    /**
     * <code>required string requestUrl = 2;</code>
     *
     * <pre>
     *请求参数
     * </pre>
     */
    public boolean hasRequestUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string requestUrl = 2;</code>
     *
     * <pre>
     *请求参数
     * </pre>
     */
    public java.lang.String getRequestUrl() {
      java.lang.Object ref = requestUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requestUrl = 2;</code>
     *
     * <pre>
     *请求参数
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRequestUrlBytes() {
      java.lang.Object ref = requestUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      requestId_ = "";
      requestUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRequestUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRequestUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.von.rpc.common.netty.proto.ProtoBufMRpcRequest}
     *
     * <pre>
     *protoc.exe -I=./ ProtoBufMRpcRequest.proto --java_out=D:/myTest/rpc/rpc-common/src/main/java
     *protoc使用注意事项：-I的路径后面跟的文件一定要隔开一个空格
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.class, com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.Builder.class);
      }

      // Construct using com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        requestUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.von.rpc.common.entity.MRpcProtoBufRequest.internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_descriptor;
      }

      public com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest getDefaultInstanceForType() {
        return com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.getDefaultInstance();
      }

      public com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest build() {
        com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest buildPartial() {
        com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest result = new com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestUrl_ = requestUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest) {
          return mergeFrom((com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest other) {
        if (other == com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000001;
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.hasRequestUrl()) {
          bitField0_ |= 0x00000002;
          requestUrl_ = other.requestUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasRequestUrl()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.von.rpc.common.entity.MRpcProtoBufRequest.ProtoBufMRpcRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string requestId = 1;
      private java.lang.Object requestId_ = "";
      /**
       * <code>required string requestId = 1;</code>
       *
       * <pre>
       *请求id
       * </pre>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string requestId = 1;</code>
       *
       * <pre>
       *请求id
       * </pre>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string requestId = 1;</code>
       *
       * <pre>
       *请求id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requestId = 1;</code>
       *
       * <pre>
       *请求id
       * </pre>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requestId = 1;</code>
       *
       * <pre>
       *请求id
       * </pre>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>required string requestId = 1;</code>
       *
       * <pre>
       *请求id
       * </pre>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }

      // required string requestUrl = 2;
      private java.lang.Object requestUrl_ = "";
      /**
       * <code>required string requestUrl = 2;</code>
       *
       * <pre>
       *请求参数
       * </pre>
       */
      public boolean hasRequestUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string requestUrl = 2;</code>
       *
       * <pre>
       *请求参数
       * </pre>
       */
      public java.lang.String getRequestUrl() {
        java.lang.Object ref = requestUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string requestUrl = 2;</code>
       *
       * <pre>
       *请求参数
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRequestUrlBytes() {
        java.lang.Object ref = requestUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requestUrl = 2;</code>
       *
       * <pre>
       *请求参数
       * </pre>
       */
      public Builder setRequestUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requestUrl = 2;</code>
       *
       * <pre>
       *请求参数
       * </pre>
       */
      public Builder clearRequestUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestUrl_ = getDefaultInstance().getRequestUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string requestUrl = 2;</code>
       *
       * <pre>
       *请求参数
       * </pre>
       */
      public Builder setRequestUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.von.rpc.common.netty.proto.ProtoBufMRpcRequest)
    }

    static {
      defaultInstance = new ProtoBufMRpcRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.von.rpc.common.netty.proto.ProtoBufMRpcRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ProtoBufMRpcRequest.proto\022\036com.von.rpc" +
      ".common.netty.proto\"y\n\023ProtoBufMRpcReque" +
      "st\022\021\n\trequestId\030\001 \002(\t\022\022\n\nrequestUrl\030\002 \002(" +
      "\t\032;\n\nMRpcMethod\022\014\n\004name\030\001 \002(\t\022\014\n\004args\030\002 " +
      "\003(\t\022\021\n\tparamType\030\003 \003(\tB0\n\031com.von.rpc.co" +
      "mmon.entityB\023MRpcProtoBufRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_descriptor,
              new java.lang.String[] { "RequestId", "RequestUrl", });
          internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_descriptor =
            internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_descriptor.getNestedTypes().get(0);
          internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_von_rpc_common_netty_proto_ProtoBufMRpcRequest_MRpcMethod_descriptor,
              new java.lang.String[] { "Name", "Args", "ParamType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
